name: "Build and Deploy"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: Install go-swagger
        run: |
          git clone https://github.com/go-swagger/go-swagger
          cd go-swagger
          go build -o ../swagger ./cmd/swagger
      - name: Generate model
        run: |
          cd hello-world/data; ../../swagger generate model --spec=spec.json
      - name: Test
        run: make test
  publish:
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: Install go-swagger
        run: |
          git clone https://github.com/go-swagger/go-swagger
          cd go-swagger
          go build -o ../swagger ./cmd/swagger
      - name: Generate model
        run: |
          cd hello-world/data; ../../swagger generate model --spec=spec.json
      - name: sam build
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "build"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      - name: Deploy to AWS
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "deploy --resolve-s3 --region ${{secrets.AWS_REGION}} --no-fail-on-empty-changeset"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
